/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _DIR2_H_RPCGEN
#define _DIR2_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct matrices_ult {
	struct {
		u_int v1_len;
		float *v1_val;
	} v1;
	int v1_f;
	int v1_c;
	struct {
		u_int v2_len;
		float *v2_val;
	} v2;
	int v2_f;
	int v2_c;
};
typedef struct matrices_ult matrices_ult;

struct matrizyescalar_ult {
	struct {
		u_int v1_len;
		float *v1_val;
	} v1;
	int v1_f;
	int v1_c;
	float num;
};
typedef struct matrizyescalar_ult matrizyescalar_ult;

struct matriz_ult {
	struct {
		u_int v1_len;
		float *v1_val;
	} v1;
	int v1_f;
	int v1_c;
};
typedef struct matriz_ult matriz_ult;

struct tipo_matriz_ult {
	int errno;
	union {
		matriz_ult m;
	} tipo_matriz_ult_u;
};
typedef struct tipo_matriz_ult tipo_matriz_ult;

#define DIRPROG_ULT 0x20000156
#define DIRVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define SUMA_MATRICES_ULT 1
extern  tipo_matriz_ult * suma_matrices_ult_1(matrices_ult , CLIENT *);
extern  tipo_matriz_ult * suma_matrices_ult_1_svc(matrices_ult , struct svc_req *);
#define RESTA_MATRICES_ULT 2
extern  tipo_matriz_ult * resta_matrices_ult_1(matrices_ult , CLIENT *);
extern  tipo_matriz_ult * resta_matrices_ult_1_svc(matrices_ult , struct svc_req *);
#define PRODUCTO_MATRICES_ULT 3
extern  tipo_matriz_ult * producto_matrices_ult_1(matrices_ult , CLIENT *);
extern  tipo_matriz_ult * producto_matrices_ult_1_svc(matrices_ult , struct svc_req *);
#define MULTI_MATRIZ_ESCALAR_ULT 4
extern  tipo_matriz_ult * multi_matriz_escalar_ult_1(matrizyescalar_ult , CLIENT *);
extern  tipo_matriz_ult * multi_matriz_escalar_ult_1_svc(matrizyescalar_ult , struct svc_req *);
#define DIVI_MATRIZ_ESCALAR_ULT 5
extern  tipo_matriz_ult * divi_matriz_escalar_ult_1(matrizyescalar_ult , CLIENT *);
extern  tipo_matriz_ult * divi_matriz_escalar_ult_1_svc(matrizyescalar_ult , struct svc_req *);
extern int dirprog_ult_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SUMA_MATRICES_ULT 1
extern  tipo_matriz_ult * suma_matrices_ult_1();
extern  tipo_matriz_ult * suma_matrices_ult_1_svc();
#define RESTA_MATRICES_ULT 2
extern  tipo_matriz_ult * resta_matrices_ult_1();
extern  tipo_matriz_ult * resta_matrices_ult_1_svc();
#define PRODUCTO_MATRICES_ULT 3
extern  tipo_matriz_ult * producto_matrices_ult_1();
extern  tipo_matriz_ult * producto_matrices_ult_1_svc();
#define MULTI_MATRIZ_ESCALAR_ULT 4
extern  tipo_matriz_ult * multi_matriz_escalar_ult_1();
extern  tipo_matriz_ult * multi_matriz_escalar_ult_1_svc();
#define DIVI_MATRIZ_ESCALAR_ULT 5
extern  tipo_matriz_ult * divi_matriz_escalar_ult_1();
extern  tipo_matriz_ult * divi_matriz_escalar_ult_1_svc();
extern int dirprog_ult_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_matrices_ult (XDR *, matrices_ult*);
extern  bool_t xdr_matrizyescalar_ult (XDR *, matrizyescalar_ult*);
extern  bool_t xdr_matriz_ult (XDR *, matriz_ult*);
extern  bool_t xdr_tipo_matriz_ult (XDR *, tipo_matriz_ult*);

#else /* K&R C */
extern bool_t xdr_matrices_ult ();
extern bool_t xdr_matrizyescalar_ult ();
extern bool_t xdr_matriz_ult ();
extern bool_t xdr_tipo_matriz_ult ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_DIR2_H_RPCGEN */
