/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "dir.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static tipo_simple *
_suma_1 (operacion  *argp, struct svc_req *rqstp)
{
	return (suma_1_svc(*argp, rqstp));
}

static tipo_simple *
_resta_1 (operacion  *argp, struct svc_req *rqstp)
{
	return (resta_1_svc(*argp, rqstp));
}

static tipo_simple *
_multiplicacion_1 (operacion  *argp, struct svc_req *rqstp)
{
	return (multiplicacion_1_svc(*argp, rqstp));
}

static tipo_simple *
_division_1 (operacion  *argp, struct svc_req *rqstp)
{
	return (division_1_svc(*argp, rqstp));
}

static tipo_vector *
_suma_vectores_1 (vectores  *argp, struct svc_req *rqstp)
{
	return (suma_vectores_1_svc(*argp, rqstp));
}

static tipo_vector *
_resta_vectores_1 (vectores  *argp, struct svc_req *rqstp)
{
	return (resta_vectores_1_svc(*argp, rqstp));
}

static tipo_simple *
_producto_escalar_1 (vectores  *argp, struct svc_req *rqstp)
{
	return (producto_escalar_1_svc(*argp, rqstp));
}

static tipo_vector *
_multi_vector_escalar_1 (vectoryescalar  *argp, struct svc_req *rqstp)
{
	return (multi_vector_escalar_1_svc(*argp, rqstp));
}

static tipo_vector *
_divi_vector_escalar_1 (vectoryescalar  *argp, struct svc_req *rqstp)
{
	return (divi_vector_escalar_1_svc(*argp, rqstp));
}

static void
dirprog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		operacion suma_1_arg;
		operacion resta_1_arg;
		operacion multiplicacion_1_arg;
		operacion division_1_arg;
		vectores suma_vectores_1_arg;
		vectores resta_vectores_1_arg;
		vectores producto_escalar_1_arg;
		vectoryescalar multi_vector_escalar_1_arg;
		vectoryescalar divi_vector_escalar_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case SUMA:
		_xdr_argument = (xdrproc_t) xdr_operacion;
		_xdr_result = (xdrproc_t) xdr_tipo_simple;
		local = (char *(*)(char *, struct svc_req *)) _suma_1;
		break;

	case RESTA:
		_xdr_argument = (xdrproc_t) xdr_operacion;
		_xdr_result = (xdrproc_t) xdr_tipo_simple;
		local = (char *(*)(char *, struct svc_req *)) _resta_1;
		break;

	case MULTIPLICACION:
		_xdr_argument = (xdrproc_t) xdr_operacion;
		_xdr_result = (xdrproc_t) xdr_tipo_simple;
		local = (char *(*)(char *, struct svc_req *)) _multiplicacion_1;
		break;

	case DIVISION:
		_xdr_argument = (xdrproc_t) xdr_operacion;
		_xdr_result = (xdrproc_t) xdr_tipo_simple;
		local = (char *(*)(char *, struct svc_req *)) _division_1;
		break;

	case SUMA_VECTORES:
		_xdr_argument = (xdrproc_t) xdr_vectores;
		_xdr_result = (xdrproc_t) xdr_tipo_vector;
		local = (char *(*)(char *, struct svc_req *)) _suma_vectores_1;
		break;

	case RESTA_VECTORES:
		_xdr_argument = (xdrproc_t) xdr_vectores;
		_xdr_result = (xdrproc_t) xdr_tipo_vector;
		local = (char *(*)(char *, struct svc_req *)) _resta_vectores_1;
		break;

	case PRODUCTO_ESCALAR:
		_xdr_argument = (xdrproc_t) xdr_vectores;
		_xdr_result = (xdrproc_t) xdr_tipo_simple;
		local = (char *(*)(char *, struct svc_req *)) _producto_escalar_1;
		break;

	case MULTI_VECTOR_ESCALAR:
		_xdr_argument = (xdrproc_t) xdr_vectoryescalar;
		_xdr_result = (xdrproc_t) xdr_tipo_vector;
		local = (char *(*)(char *, struct svc_req *)) _multi_vector_escalar_1;
		break;

	case DIVI_VECTOR_ESCALAR:
		_xdr_argument = (xdrproc_t) xdr_vectoryescalar;
		_xdr_result = (xdrproc_t) xdr_tipo_vector;
		local = (char *(*)(char *, struct svc_req *)) _divi_vector_escalar_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (DIRPROG, DIRVER);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, DIRPROG, DIRVER, dirprog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (DIRPROG, DIRVER, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, DIRPROG, DIRVER, dirprog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (DIRPROG, DIRVER, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
