/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "dir.h"

tipo *
suma_1_svc(operacion arg1,  struct svc_req *rqstp)
{
	static tipo  result;
	result.tipo_u.resultado = arg1.firstparam + arg1.secondparam;
	/*
	 * insert server code here
	 */

	return &result;
}

tipo *
resta_1_svc(operacion arg1,  struct svc_req *rqstp)
{
	static tipo  result;
	result.tipo_u.resultado = arg1.firstparam - arg1.secondparam;
	/*
	 * insert server code here
	 */

	return &result;
}

tipo *
multiplicacion_1_svc(operacion arg1,  struct svc_req *rqstp)
{
	static tipo  result;
	result.tipo_u.resultado = arg1.firstparam * arg1.secondparam;
	/*
	 * insert server code here
	 */

	return &result;
}

tipo *
division_1_svc(operacion arg1,  struct svc_req *rqstp)
{
	static tipo  result;
	result.tipo_u.resultado = arg1.firstparam / arg1.secondparam;
	/*
	 * insert server code here
	 */

	return &result;
}
