/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "dir.h"

bool_t
xdr_operacion (XDR *xdrs, operacion *objp)
{
	register int32_t *buf;

	 if (!xdr_float (xdrs, &objp->firstparam))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->secondparam))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_tipo (XDR *xdrs, tipo *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->errno))
		 return FALSE;
	switch (objp->errno) {
	case 0:
		 if (!xdr_float (xdrs, &objp->tipo_u.resultado))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}
