/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "dir.h"


void
dirprog_1(char *host)
{
	CLIENT *clnt;
	tipo  *result_1;
	operacion suma_1_arg1;
	tipo  *result_2;
	operacion resta_1_arg1;
	tipo  *result_3;
	operacion multiplicacion_1_arg1;
	tipo  *result_4;
	operacion division_1_arg1;
	char operacion;
	float operando1, operando2;
	char opcion;
	char terminado = 'n';
	int primeravez = 1;
	float resultado = 0;


#ifndef	DEBUG
	clnt = clnt_create (host, DIRPROG, DIRVER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	
	while (opcion != 'q'){
		printf("=======CALCULADORA========\n");
		printf("Operaciones simples: s\n");
		printf("Operaciones con polinomios: p\n");
		printf("Operaciones con vectores: v\n");
		printf("Operaciones con matrices: m\n");
		printf("Salir: q\n");
		scanf("%c",&opcion);
		while(opcion == ' ' || opcion == '\n'){
			scanf("%c",&opcion);

		}

		while(opcion != 's' && opcion != 'p' && opcion != 'v' && opcion != 'm' && opcion != 'q'){
			printf("\nIntroduzca una opción correcta\n");
			printf("Operaciones simples: s\n");
			printf("Operaciones con polinomios: p\n");
			printf("Operaciones con vectores: v\n");
			printf("Operaciones con matrices: m\n");
			printf("Salir: q\n");
			scanf("%c",&opcion);
			while(opcion==' ' || opcion == '\n'){
				scanf("%c",&opcion);
			}

		}
		switch(opcion){
			case 's':
				while(terminado != 's'){
				
				if(primeravez!=1){
					operando1 = resultado;
					printf("%f",operando1);
				}
				
				if(primeravez){
					printf("Introduzca la operacion (ej: '4 + 5'):\n");
					scanf("%f",&operando1);
					while((operando1 == '\n' || operando1 == ' ')){
						scanf("%f",&operando1);
					}

					primeravez=0;
				}
				
				scanf("%c",&operacion);
				while(operacion == '\n'  || operacion == ' '){
					scanf("%c",&operacion);
				}
				
				scanf("%f",&operando2);
				while(operando2 == '\n' || operando2 == ' '){
					scanf("%f",&operando2);
				}
									printf("--->%f %c %f\n",operando1,operacion,operando2);
				if(operacion == '+'){
					printf("--->%f %c %f\n",operando1,operacion,operando2);
					suma_1_arg1.firstparam = operando1;
					suma_1_arg1.secondparam = operando2;
					result_1 = suma_1(suma_1_arg1, clnt);
					if (result_1 == (tipo *) NULL) {
						clnt_perror (clnt, "call failed");
					}
					resultado = (*result_1).tipo_u.resultado;
				}
				
				else if(operacion == '-'){
					resta_1_arg1.firstparam = operando1;
					resta_1_arg1.secondparam = operando2;
					result_2 = resta_1(resta_1_arg1, clnt);
					if (result_2 == (tipo *) NULL) {
						clnt_perror (clnt, "call failed");
					}
					resultado = (*result_2).tipo_u.resultado;
				}
				
				else if(operacion == '*'){
					multiplicacion_1_arg1.firstparam = operando1;
					multiplicacion_1_arg1.secondparam = operando2;
					result_3 = multiplicacion_1(multiplicacion_1_arg1, clnt);
					if (result_3 == (tipo *) NULL) {
						clnt_perror (clnt, "call failed");
					}
					resultado = (*result_3).tipo_u.resultado;
				}
				else if(operacion == '/'){
					division_1_arg1.firstparam = operando1;
					division_1_arg1.secondparam = operando2;
					result_4 = division_1(division_1_arg1, clnt);
					if (result_4 == (tipo *) NULL) {
						clnt_perror (clnt, "call failed");
					}
					resultado = (*result_4).tipo_u.resultado;
				}
			
			printf("%f", resultado);
			printf("\n¿Desea terminar?: ('s' para si | 'n' para no)\n");
			scanf("%c", &terminado);
			while(terminado != 's' && terminado != 'n'){
				scanf("%c",&terminado);
			}
			}
			primeravez = 1;
			terminado = 0;
			printf("\n");
			break;
		}
}
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	dirprog_1 (host);
exit (0);
}
