/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "dir2.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

tipo_matriz_ult *
suma_matrices_ult_1(matrices_ult arg1,  CLIENT *clnt)
{
	static tipo_matriz_ult clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, SUMA_MATRICES_ULT,
		(xdrproc_t) xdr_matrices_ult, (caddr_t) &arg1,
		(xdrproc_t) xdr_tipo_matriz_ult, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

tipo_matriz_ult *
resta_matrices_ult_1(matrices_ult arg1,  CLIENT *clnt)
{
	static tipo_matriz_ult clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RESTA_MATRICES_ULT,
		(xdrproc_t) xdr_matrices_ult, (caddr_t) &arg1,
		(xdrproc_t) xdr_tipo_matriz_ult, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

tipo_matriz_ult *
producto_matrices_ult_1(matrices_ult arg1,  CLIENT *clnt)
{
	static tipo_matriz_ult clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, PRODUCTO_MATRICES_ULT,
		(xdrproc_t) xdr_matrices_ult, (caddr_t) &arg1,
		(xdrproc_t) xdr_tipo_matriz_ult, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

tipo_matriz_ult *
multi_matriz_escalar_ult_1(matrizyescalar_ult arg1,  CLIENT *clnt)
{
	static tipo_matriz_ult clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, MULTI_MATRIZ_ESCALAR_ULT,
		(xdrproc_t) xdr_matrizyescalar_ult, (caddr_t) &arg1,
		(xdrproc_t) xdr_tipo_matriz_ult, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

tipo_matriz_ult *
divi_matriz_escalar_ult_1(matrizyescalar_ult arg1,  CLIENT *clnt)
{
	static tipo_matriz_ult clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, DIVI_MATRIZ_ESCALAR_ULT,
		(xdrproc_t) xdr_matrizyescalar_ult, (caddr_t) &arg1,
		(xdrproc_t) xdr_tipo_matriz_ult, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
