/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "dir2.h"

bool_t
xdr_matrices_ult (XDR *xdrs, matrices_ult *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->v1.v1_val, (u_int *) &objp->v1.v1_len, ~0,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->v1_f))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->v1_c))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->v2.v2_val, (u_int *) &objp->v2.v2_len, ~0,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->v2_f))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->v2_c))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_matrizyescalar_ult (XDR *xdrs, matrizyescalar_ult *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->v1.v1_val, (u_int *) &objp->v1.v1_len, ~0,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->v1_f))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->v1_c))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->num))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_matriz_ult (XDR *xdrs, matriz_ult *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->v1.v1_val, (u_int *) &objp->v1.v1_len, ~0,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->v1_f))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->v1_c))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_tipo_matriz_ult (XDR *xdrs, tipo_matriz_ult *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->errno))
		 return FALSE;
	switch (objp->errno) {
	case 0:
		 if (!xdr_matriz_ult (xdrs, &objp->tipo_matriz_ult_u.m))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}
