/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "dir.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static tipo_simple *
_suma_1 (operacion  *argp, struct svc_req *rqstp)
{
	return (suma_1_svc(*argp, rqstp));
}

static tipo_simple *
_resta_1 (operacion  *argp, struct svc_req *rqstp)
{
	return (resta_1_svc(*argp, rqstp));
}

static tipo_simple *
_multiplicacion_1 (operacion  *argp, struct svc_req *rqstp)
{
	return (multiplicacion_1_svc(*argp, rqstp));
}

static tipo_simple *
_division_1 (operacion  *argp, struct svc_req *rqstp)
{
	return (division_1_svc(*argp, rqstp));
}

static tipo_simple *
_potencia_1 (operacion_2  *argp, struct svc_req *rqstp)
{
	return (potencia_1_svc(*argp, rqstp));
}

static tipo_simple *
_raiz_1 (operacion_2  *argp, struct svc_req *rqstp)
{
	return (raiz_1_svc(*argp, rqstp));
}

static tipo_simple *
_logaritmo_1 (operacion_2  *argp, struct svc_req *rqstp)
{
	return (logaritmo_1_svc(*argp, rqstp));
}

static tipo_vector *
_suma_vectores_1 (vectores  *argp, struct svc_req *rqstp)
{
	return (suma_vectores_1_svc(*argp, rqstp));
}

static tipo_vector *
_resta_vectores_1 (vectores  *argp, struct svc_req *rqstp)
{
	return (resta_vectores_1_svc(*argp, rqstp));
}

static tipo_simple *
_producto_escalar_1 (vectores  *argp, struct svc_req *rqstp)
{
	return (producto_escalar_1_svc(*argp, rqstp));
}

static tipo_vector *
_multi_vector_escalar_1 (vectoryescalar  *argp, struct svc_req *rqstp)
{
	return (multi_vector_escalar_1_svc(*argp, rqstp));
}

static tipo_vector *
_divi_vector_escalar_1 (vectoryescalar  *argp, struct svc_req *rqstp)
{
	return (divi_vector_escalar_1_svc(*argp, rqstp));
}

static tipo_matriz *
_suma_matrices_1 (matrices  *argp, struct svc_req *rqstp)
{
	return (suma_matrices_1_svc(*argp, rqstp));
}

static tipo_matriz *
_resta_matrices_1 (matrices  *argp, struct svc_req *rqstp)
{
	return (resta_matrices_1_svc(*argp, rqstp));
}

static tipo_matriz *
_producto_matrices_1 (matrices  *argp, struct svc_req *rqstp)
{
	return (producto_matrices_1_svc(*argp, rqstp));
}

static tipo_matriz *
_multi_matriz_escalar_1 (matrizyescalar  *argp, struct svc_req *rqstp)
{
	return (multi_matriz_escalar_1_svc(*argp, rqstp));
}

static tipo_matriz *
_divi_matriz_escalar_1 (matrizyescalar  *argp, struct svc_req *rqstp)
{
	return (divi_matriz_escalar_1_svc(*argp, rqstp));
}

static tipo_fraccion *
_suma_fracciones_1 (fracciones  *argp, struct svc_req *rqstp)
{
	return (suma_fracciones_1_svc(*argp, rqstp));
}

static tipo_fraccion *
_resta_fracciones_1 (fracciones  *argp, struct svc_req *rqstp)
{
	return (resta_fracciones_1_svc(*argp, rqstp));
}

static tipo_fraccion *
_multi_fracciones_1 (fracciones  *argp, struct svc_req *rqstp)
{
	return (multi_fracciones_1_svc(*argp, rqstp));
}

static tipo_fraccion *
_divi_fracciones_1 (fracciones  *argp, struct svc_req *rqstp)
{
	return (divi_fracciones_1_svc(*argp, rqstp));
}

static tipo_fraccion *
_simplificar_fraccion_1 (fraccion  *argp, struct svc_req *rqstp)
{
	return (simplificar_fraccion_1_svc(*argp, rqstp));
}

static void
dirprog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		operacion suma_1_arg;
		operacion resta_1_arg;
		operacion multiplicacion_1_arg;
		operacion division_1_arg;
		operacion_2 potencia_1_arg;
		operacion_2 raiz_1_arg;
		operacion_2 logaritmo_1_arg;
		vectores suma_vectores_1_arg;
		vectores resta_vectores_1_arg;
		vectores producto_escalar_1_arg;
		vectoryescalar multi_vector_escalar_1_arg;
		vectoryescalar divi_vector_escalar_1_arg;
		matrices suma_matrices_1_arg;
		matrices resta_matrices_1_arg;
		matrices producto_matrices_1_arg;
		matrizyescalar multi_matriz_escalar_1_arg;
		matrizyescalar divi_matriz_escalar_1_arg;
		fracciones suma_fracciones_1_arg;
		fracciones resta_fracciones_1_arg;
		fracciones multi_fracciones_1_arg;
		fracciones divi_fracciones_1_arg;
		fraccion simplificar_fraccion_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case SUMA:
		_xdr_argument = (xdrproc_t) xdr_operacion;
		_xdr_result = (xdrproc_t) xdr_tipo_simple;
		local = (char *(*)(char *, struct svc_req *)) _suma_1;
		break;

	case RESTA:
		_xdr_argument = (xdrproc_t) xdr_operacion;
		_xdr_result = (xdrproc_t) xdr_tipo_simple;
		local = (char *(*)(char *, struct svc_req *)) _resta_1;
		break;

	case MULTIPLICACION:
		_xdr_argument = (xdrproc_t) xdr_operacion;
		_xdr_result = (xdrproc_t) xdr_tipo_simple;
		local = (char *(*)(char *, struct svc_req *)) _multiplicacion_1;
		break;

	case DIVISION:
		_xdr_argument = (xdrproc_t) xdr_operacion;
		_xdr_result = (xdrproc_t) xdr_tipo_simple;
		local = (char *(*)(char *, struct svc_req *)) _division_1;
		break;

	case POTENCIA:
		_xdr_argument = (xdrproc_t) xdr_operacion_2;
		_xdr_result = (xdrproc_t) xdr_tipo_simple;
		local = (char *(*)(char *, struct svc_req *)) _potencia_1;
		break;

	case RAIZ:
		_xdr_argument = (xdrproc_t) xdr_operacion_2;
		_xdr_result = (xdrproc_t) xdr_tipo_simple;
		local = (char *(*)(char *, struct svc_req *)) _raiz_1;
		break;

	case LOGARITMO:
		_xdr_argument = (xdrproc_t) xdr_operacion_2;
		_xdr_result = (xdrproc_t) xdr_tipo_simple;
		local = (char *(*)(char *, struct svc_req *)) _logaritmo_1;
		break;

	case SUMA_VECTORES:
		_xdr_argument = (xdrproc_t) xdr_vectores;
		_xdr_result = (xdrproc_t) xdr_tipo_vector;
		local = (char *(*)(char *, struct svc_req *)) _suma_vectores_1;
		break;

	case RESTA_VECTORES:
		_xdr_argument = (xdrproc_t) xdr_vectores;
		_xdr_result = (xdrproc_t) xdr_tipo_vector;
		local = (char *(*)(char *, struct svc_req *)) _resta_vectores_1;
		break;

	case PRODUCTO_ESCALAR:
		_xdr_argument = (xdrproc_t) xdr_vectores;
		_xdr_result = (xdrproc_t) xdr_tipo_simple;
		local = (char *(*)(char *, struct svc_req *)) _producto_escalar_1;
		break;

	case MULTI_VECTOR_ESCALAR:
		_xdr_argument = (xdrproc_t) xdr_vectoryescalar;
		_xdr_result = (xdrproc_t) xdr_tipo_vector;
		local = (char *(*)(char *, struct svc_req *)) _multi_vector_escalar_1;
		break;

	case DIVI_VECTOR_ESCALAR:
		_xdr_argument = (xdrproc_t) xdr_vectoryescalar;
		_xdr_result = (xdrproc_t) xdr_tipo_vector;
		local = (char *(*)(char *, struct svc_req *)) _divi_vector_escalar_1;
		break;

	case SUMA_MATRICES:
		_xdr_argument = (xdrproc_t) xdr_matrices;
		_xdr_result = (xdrproc_t) xdr_tipo_matriz;
		local = (char *(*)(char *, struct svc_req *)) _suma_matrices_1;
		break;

	case RESTA_MATRICES:
		_xdr_argument = (xdrproc_t) xdr_matrices;
		_xdr_result = (xdrproc_t) xdr_tipo_matriz;
		local = (char *(*)(char *, struct svc_req *)) _resta_matrices_1;
		break;

	case PRODUCTO_MATRICES:
		_xdr_argument = (xdrproc_t) xdr_matrices;
		_xdr_result = (xdrproc_t) xdr_tipo_matriz;
		local = (char *(*)(char *, struct svc_req *)) _producto_matrices_1;
		break;

	case MULTI_MATRIZ_ESCALAR:
		_xdr_argument = (xdrproc_t) xdr_matrizyescalar;
		_xdr_result = (xdrproc_t) xdr_tipo_matriz;
		local = (char *(*)(char *, struct svc_req *)) _multi_matriz_escalar_1;
		break;

	case DIVI_MATRIZ_ESCALAR:
		_xdr_argument = (xdrproc_t) xdr_matrizyescalar;
		_xdr_result = (xdrproc_t) xdr_tipo_matriz;
		local = (char *(*)(char *, struct svc_req *)) _divi_matriz_escalar_1;
		break;

	case SUMA_FRACCIONES:
		_xdr_argument = (xdrproc_t) xdr_fracciones;
		_xdr_result = (xdrproc_t) xdr_tipo_fraccion;
		local = (char *(*)(char *, struct svc_req *)) _suma_fracciones_1;
		break;

	case RESTA_FRACCIONES:
		_xdr_argument = (xdrproc_t) xdr_fracciones;
		_xdr_result = (xdrproc_t) xdr_tipo_fraccion;
		local = (char *(*)(char *, struct svc_req *)) _resta_fracciones_1;
		break;

	case MULTI_FRACCIONES:
		_xdr_argument = (xdrproc_t) xdr_fracciones;
		_xdr_result = (xdrproc_t) xdr_tipo_fraccion;
		local = (char *(*)(char *, struct svc_req *)) _multi_fracciones_1;
		break;

	case DIVI_FRACCIONES:
		_xdr_argument = (xdrproc_t) xdr_fracciones;
		_xdr_result = (xdrproc_t) xdr_tipo_fraccion;
		local = (char *(*)(char *, struct svc_req *)) _divi_fracciones_1;
		break;

	case SIMPLIFICAR_FRACCION:
		_xdr_argument = (xdrproc_t) xdr_fraccion;
		_xdr_result = (xdrproc_t) xdr_tipo_fraccion;
		local = (char *(*)(char *, struct svc_req *)) _simplificar_fraccion_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (DIRPROG, DIRVER);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, DIRPROG, DIRVER, dirprog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (DIRPROG, DIRVER, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, DIRPROG, DIRVER, dirprog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (DIRPROG, DIRVER, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
