/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "dir.h"

int *
calculadora_1_svc(struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	 result = 9;

	return &result;
}
