/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "dir.h"


void
dirprog_1(char *host, int n1, int n2, char operacion)
{
	CLIENT *clnt;
	int  *result_1;

#ifndef	DEBUG
	clnt = clnt_create (host, DIRPROG, DIRVER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = calculadora_1(clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	
	printf("%d\n",*result_1);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	int n1, n2;
	char operacion;
	
	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	n1 = argv[2];
	n2 = argv[4];
	operacion = argv[3];
	
	dirprog_1 (host, n1, n2, operacion);
exit (0);
}
