/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "dir2.h"


void
dirprog_ult_1(char *host)
{
	CLIENT *clnt;
	tipo_matriz_ult  *result_1;
	matrices_ult suma_matrices_ult_1_arg1;
	tipo_matriz_ult  *result_2;
	matrices_ult resta_matrices_ult_1_arg1;
	tipo_matriz_ult  *result_3;
	matrices_ult producto_matrices_ult_1_arg1;
	tipo_matriz_ult  *result_4;
	matrizyescalar_ult multi_matriz_escalar_ult_1_arg1;
	tipo_matriz_ult  *result_5;
	matrizyescalar_ult divi_matriz_escalar_ult_1_arg1;

#ifndef	DEBUG
	clnt = clnt_create (host, DIRPROG_ULT, DIRVER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = suma_matrices_ult_1(suma_matrices_ult_1_arg1, clnt);
	if (result_1 == (tipo_matriz_ult *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = resta_matrices_ult_1(resta_matrices_ult_1_arg1, clnt);
	if (result_2 == (tipo_matriz_ult *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = producto_matrices_ult_1(producto_matrices_ult_1_arg1, clnt);
	if (result_3 == (tipo_matriz_ult *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = multi_matriz_escalar_ult_1(multi_matriz_escalar_ult_1_arg1, clnt);
	if (result_4 == (tipo_matriz_ult *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_5 = divi_matriz_escalar_ult_1(divi_matriz_escalar_ult_1_arg1, clnt);
	if (result_5 == (tipo_matriz_ult *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	dirprog_ult_1 (host);
exit (0);
}
