/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "dir2.h"

tipo_matriz *
suma_matrices_ult_1_svc(matrices arg1,  struct svc_req *rqstp)
{
	static tipo_matriz  result;

	/*
	 * insert server code here
	 */

	return &result;
}

tipo_matriz *
resta_matrices_ult_1_svc(matrices arg1,  struct svc_req *rqstp)
{
	static tipo_matriz  result;

	/*
	 * insert server code here
	 */

	return &result;
}

tipo_matriz *
producto_matrices_ult_1_svc(matrices arg1,  struct svc_req *rqstp)
{
	static tipo_matriz  result;
	if(arg1.v1_c == arg1.v2_f){
		result.tipo_matriz_u.m.v1_c = arg1.v2_c;
		result.tipo_matriz_u.m.v1_f = arg1.v1_f;
	}

		result.tipo_matriz_u.m.v1.v1_len = result.tipo_matriz_u.m.v1_c*result.tipo_matriz_u.m.v1_f;
		result.tipo_matriz_u.m.v1.v1_val = (float*) malloc(result.tipo_matriz_u.m.v1.v1_len*sizeof(float));
		float suma;
		for(int f = 0; f < arg1.v1_f; f++){
			for(int c = 0; c < arg1.v2_c; c++){
				suma = 0;
				for(int k = 0; k < arg1.v1_c; k++){
					suma += arg1.v1.v1_val[f*arg1.v1_c+k] * arg1.v2.v2_val[k*arg1.v2_c + c];
				}
				result.tipo_matriz_u.m.v1.v1_val[f*result.tipo_matriz_u.m.v1_c+c] = suma;
			}
		}
}

tipo_matriz *
multi_matriz_escalar_ult_1_svc(matrizyescalar arg1,  struct svc_req *rqstp)
{
	static tipo_matriz  result;

	/*
	 * insert server code here
	 */

	return &result;
}

tipo_matriz *
divi_matriz_escalar_ult_1_svc(matrizyescalar arg1,  struct svc_req *rqstp)
{
	static tipo_matriz  result;

	/*
	 * insert server code here
	 */

	return &result;
}
