/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "dir.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

tipo_simple *
suma_1(operacion *argp, CLIENT *clnt)
{
	static tipo_simple clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, SUMA,
		(xdrproc_t) xdr_operacion, (caddr_t) argp,
		(xdrproc_t) xdr_tipo_simple, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

tipo_simple *
resta_1(operacion *argp, CLIENT *clnt)
{
	static tipo_simple clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RESTA,
		(xdrproc_t) xdr_operacion, (caddr_t) argp,
		(xdrproc_t) xdr_tipo_simple, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

tipo_simple *
multiplicacion_1(operacion *argp, CLIENT *clnt)
{
	static tipo_simple clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, MULTIPLICACION,
		(xdrproc_t) xdr_operacion, (caddr_t) argp,
		(xdrproc_t) xdr_tipo_simple, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

tipo_simple *
division_1(operacion *argp, CLIENT *clnt)
{
	static tipo_simple clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, DIVISION,
		(xdrproc_t) xdr_operacion, (caddr_t) argp,
		(xdrproc_t) xdr_tipo_simple, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

tipo_vector *
suma_vectores_1(vectores *argp, CLIENT *clnt)
{
	static tipo_vector clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, SUMA_VECTORES,
		(xdrproc_t) xdr_vectores, (caddr_t) argp,
		(xdrproc_t) xdr_tipo_vector, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

tipo_vector *
resta_vectores_1(vectores *argp, CLIENT *clnt)
{
	static tipo_vector clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RESTA_VECTORES,
		(xdrproc_t) xdr_vectores, (caddr_t) argp,
		(xdrproc_t) xdr_tipo_vector, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

tipo_vector *
multiplicacion_vectores_1(vectores *argp, CLIENT *clnt)
{
	static tipo_vector clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, MULTIPLICACION_VECTORES,
		(xdrproc_t) xdr_vectores, (caddr_t) argp,
		(xdrproc_t) xdr_tipo_vector, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

tipo_vector *
division_vectores_1(vectores *argp, CLIENT *clnt)
{
	static tipo_vector clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, DIVISION_VECTORES,
		(xdrproc_t) xdr_vectores, (caddr_t) argp,
		(xdrproc_t) xdr_tipo_vector, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
