/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "dir.h"

bool_t
xdr_operacion (XDR *xdrs, operacion *objp)
{
	register int32_t *buf;

	 if (!xdr_float (xdrs, &objp->firstparam))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->secondparam))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_vectores (XDR *xdrs, vectores *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->v1.v1_val, (u_int *) &objp->v1.v1_len, ~0,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->v2.v2_val, (u_int *) &objp->v2.v2_len, ~0,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_tipo_simple (XDR *xdrs, tipo_simple *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->errno))
		 return FALSE;
	switch (objp->errno) {
	case 0:
		 if (!xdr_float (xdrs, &objp->tipo_simple_u.resultado))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_tipo_vector (XDR *xdrs, tipo_vector *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->errno))
		 return FALSE;
	switch (objp->errno) {
	case 0:
		 if (!xdr_array (xdrs, (char **)&objp->tipo_vector_u.resultado.resultado_val, (u_int *) &objp->tipo_vector_u.resultado.resultado_len, ~0,
			sizeof (float), (xdrproc_t) xdr_float))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}
