/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "dir.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
dirprog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		operacion suma_1_arg;
		operacion resta_1_arg;
		operacion multiplicacion_1_arg;
		operacion division_1_arg;
		vectores suma_vectores_1_arg;
		vectores resta_vectores_1_arg;
		vectores multiplicacion_vectores_1_arg;
		vectores division_vectores_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case SUMA:
		_xdr_argument = (xdrproc_t) xdr_operacion;
		_xdr_result = (xdrproc_t) xdr_tipo_simple;
		local = (char *(*)(char *, struct svc_req *)) suma_1_svc;
		break;

	case RESTA:
		_xdr_argument = (xdrproc_t) xdr_operacion;
		_xdr_result = (xdrproc_t) xdr_tipo_simple;
		local = (char *(*)(char *, struct svc_req *)) resta_1_svc;
		break;

	case MULTIPLICACION:
		_xdr_argument = (xdrproc_t) xdr_operacion;
		_xdr_result = (xdrproc_t) xdr_tipo_simple;
		local = (char *(*)(char *, struct svc_req *)) multiplicacion_1_svc;
		break;

	case DIVISION:
		_xdr_argument = (xdrproc_t) xdr_operacion;
		_xdr_result = (xdrproc_t) xdr_tipo_simple;
		local = (char *(*)(char *, struct svc_req *)) division_1_svc;
		break;

	case SUMA_VECTORES:
		_xdr_argument = (xdrproc_t) xdr_vectores;
		_xdr_result = (xdrproc_t) xdr_tipo_vector;
		local = (char *(*)(char *, struct svc_req *)) suma_vectores_1_svc;
		break;

	case RESTA_VECTORES:
		_xdr_argument = (xdrproc_t) xdr_vectores;
		_xdr_result = (xdrproc_t) xdr_tipo_vector;
		local = (char *(*)(char *, struct svc_req *)) resta_vectores_1_svc;
		break;

	case MULTIPLICACION_VECTORES:
		_xdr_argument = (xdrproc_t) xdr_vectores;
		_xdr_result = (xdrproc_t) xdr_tipo_vector;
		local = (char *(*)(char *, struct svc_req *)) multiplicacion_vectores_1_svc;
		break;

	case DIVISION_VECTORES:
		_xdr_argument = (xdrproc_t) xdr_vectores;
		_xdr_result = (xdrproc_t) xdr_tipo_vector;
		local = (char *(*)(char *, struct svc_req *)) division_vectores_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (DIRPROG, DIRVER);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, DIRPROG, DIRVER, dirprog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (DIRPROG, DIRVER, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, DIRPROG, DIRVER, dirprog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (DIRPROG, DIRVER, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
